version: '3.4'
services:
  jaeger:
    container_name: "jaeger-container"
    ports:
      - 4317:4317 #grpc
      - 4318:4318 #http
      - 16686:16686 #UI
  zipkin:
    container_name: "zipkin-conteiner"
    ports:
      - 9411:9411
  redis:
    container_name: "redis-container"
    ports:
      - 6379:6379